version: "3.9"

services:
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github
    ports:
      - 5588:5432
